FROM ros:jazzy

ENV DEBIAN_FRONTED=noninteractive

RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTf-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8

RUN apt install -y software-proporties-common curl
RUN add-apt-repository universe

RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" && \
    dpkg -i /tmp/ros2-apt-source.deb

RUN apt update && apt install -y ros-kilted-desktop ros-dev-tools python3-pip

WORKDIR /app/agentes_cooperacion
COPY ./agentes_cooperacion/src ./src

RUN rosdep init && rosdep update && \
    rosdep install --from-paths src --ignore-src -y && \
    . /opt/ros/kilted/setup.sh && \
    colcon build --packages-select agente_pkg

RUN echo "source /opt/ros/kilted/setup.bash" >> ~/.bashrc && \
    echo "source /app/agentes_cooperacion/install/setup.bash" >> ~/.bashrc

CMD ["bash"]